// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { CheckBox, GridBox, ListView, ScrollView, VerticalBox , Button} from "std-widgets.slint";


export component Page inherits VerticalBox {
    in property<string> title: "title";
    in property<string> description: "description";

    HorizontalLayout {
        height: 1px;
   

        // Spacer
     

    }

    @children
}