import { CheckBox, StandardListView, StyleMetrics } from "std-widgets.slint";
import { ListViewPage } from "./pages/pages.slint";

import { ListViewData, ListViewItem, FileAction, ListItemProgress } from "./global_struct.slint";

export { ListViewData, ListViewItem, FileAction, ListItemProgress}


import "./fonts/NotoSans-Regular.ttf"; 
import "./fonts/NotoSans-Bold.ttf";



// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial





export component App inherits Window {
    preferred-width: 1700px;
    min-width: 900px;
    preferred-height: 600px;
    

    title: "备份小鸡子";
    icon: @image-url("images/icon.jpg");
  




    VerticalLayout {
   
        

        
        ListViewPage {
            title:"";
        }

       
    }
}
