// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

export struct ListViewItem{
    checked: bool,
    name: string,
    size: int,
    modified_time: string,
    create_time: string,
    size_show: string,
    file_type: string,
    show: bool
}


export struct ListItemProgress {

    total:int,
    moved:int,
    status:int
}

// export global Functions {
  

//     public pure function get-file-icon(name: string) -> image {
//         // if (name.)
//         if (name == "ae"){
//             return @image-url("./images/file_type/ae.png");
//         }else if (name == "ai" || name == "eps"){
//             return @image-url("./images/file_type/ai eps.png");
//         }else if (name == "doc" || name == "docx"){
//             return @image-url("./images/file_type/doc rtf.png");
//         }else if (name == "html" || name == "htm"){
//             return @image-url("./images/file_type/html htm IE.png");
//         }else if (name == "mpeg" || name == "avi" || name == "wav" || name == "ogg" || name == "mp3" || name == "mp4" || name == "mkv"){
//             return @image-url("./images/file_type/mpeg avi wav ogg mp3.png");
//         }else if (name == "pdf"){
//             return @image-url("./images/file_type/pdf.png");
//         }else if (name == "ppt"){
//             return @image-url("./images/file_type/ppt.png");
//         }else if (name == "torrent"){
//             return @image-url("./images/file_type/torrent.png");
//         }else if (name == "xls" || name == "xlsx" || name == "csv" || name == "xlsm"){
//             return @image-url("./images/file_type/xls.png");
//         }else if (name == "zip" || name == "rar" || name == "7z"){
//             return @image-url("./images/file_type/zip rar.png");
//         }
//         else{
//             return @image-url("./images/scan.svg");
//         }
//     }
// }


export global ListViewData  {
    callback sort-by(int, bool);
    callback select-all();
    
    callback search-by-name(string);
    in property <float> percent;
    in property <[ListItemProgress]> data-size;
    in property <bool> has-select-all:false;
    in property<[ListViewItem]> select-item;
    // [
    // {
    // checked:false,name:"111iohbb8908hnnmmsdadsadasasdasdasddaasdasdasdasdasdasdasdasdasdasdasdasddasdadasd.jpg",
    // create_time:"2023-01-01 08:00:00",
    // size:1667,
    // modified_time:"2023-01-02 08:00:00"
    // },
    
    // {
    // checked:false,name:"FFFFSwewe423424.jpg",
    // create_time:"2023-01-01 09:00:00",
    // size:1221667,
    // modified_time:"2023-01-03 08:10:03"
    // }
    
    // ];

}



export global FileAction  {
    callback get-file-list();
    callback copy-file(string, string);
    callback get-file-path(int);
    callback update-progress-status(int);
    in property <string> origin-path;
    in property <string> target-path;
}
